// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olwzjikiaxgpcgdhmhvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sd3pqaWtpYXhncGNnZGhtaHZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3Mjk3ODgsImV4cCI6MjA2NTMwNTc4OH0.mp1XlsoLGTTc0-IngCILjjbrQIiZo-f8gEPmAt5t614";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);